### ISSUE TITLE
Renamed file in working copy has issues on Git 2.11

### ISSUE THREAD

**Issue by zombiezen** [zombiezen/gg#60]
Really a bug in a semi-old version of Git, but documenting in case I come up with a way to work around.

### Steps to Reproduce

```shell
$ gg init
$ touch foo.txt
$ gg add .
$ gg commit -m "first"
$ mv foo.txt bar.txt
$ gg add bar.txt
$ gg status
```

(This was caught by the regression test for #44, so you can trigger this with `vgo test -run=TestStatus_RenamedLocally ./cmd/gg` with Git 1.11 installed.)

### Expected Behavior

status succeeds with:

```
A bar.txt
! foo.txt
```

### Actual Behavior

status exits with:

```
gg: read status entry: unexpected EOF
```

Amazingly, `git status --porcelain` produces:

```
 R foo.txt
```

Notice that this is `(space)R` code, and the name is the source instead of the destination.

### Version Info

```
gg built from source at 0eac45f8e010edcc289c22bc7a27875662e8e2a1 on 2018-07-14T22:13:58Z
go: go1.10.3 gc linux/amd64
git version 2.11.0
```

**Comment by zombiezen** [comment]
It's worth noting that 2.11 is the version of Git in [Debian Stretch](https://packages.debian.org/stretch/git), the current stable release. Sigh...

**Comment by zombiezen** [comment]
Right, the issue is that on systems that I don't have much control over (Google Cloud Shell, random stock Debian VMs, etc.) or for the average user, this adds an extra bit of complexity than just "use Git from your package manager, download gg, you're done".

I'll look into filing a bug with Debian.

**Comment by zombiezen** [comment]
I've opened [#904101](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904101) in Debian to track the underlying Git issue.

**Comment by zombiezen** [comment]
After thinking about this for a while and discussing with Brandon Williams, it seems like the best way forward is to run `git version`, check for the affected range, and disable rename detection.

**Comment by zombiezen** [comment]
I went through and tested all latest-patched major versions from Git 2.7 through Git 2.17.  The affected Git versions are 2.11 through 2.15.2.

**Comment by zombiezen** [comment]
Git ignores requests to disable rename detection (setting either `status.renames` or `diff.renames` to `false`) on these versions. 😞

**Comment by jrn** [comment]
Indeed, status.renames + --no-renames was introduced by v2.18.0-rc0~25^2 (add status config and command line options for rename detection, 2018-05-11), and status started respecting diff.renames in v2.18.0-rc0~25^2~1 (wt-status: use settings from git_diff_ui_config, 2018-05-04).

Do you know what commit introduced the problem (e.g. can you catch it with "git bisect run")?

**Comment by zombiezen** [comment]
I don't know the exact commit, but it is somewhere between 2.10 and 2.11. I just fixed this in a way that just deals with the bad output and surfaces to the user. The only thing that could make for a better experience is to disable rename detection for these versions, but I don't have more cycles to burn on this unfortunately.
